name: build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: pyama
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/pyama86/github-image-scanner:latest,pyama/github-image-scanner

  scan:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: "pyama86"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_API: "https://api.github.com/"
      RUBYOPT: "-W0"
    container:
      image: pyama/github-image-scanner:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Cache Trivy
        uses: actions/cache@v2
        with:
          path: |
            /opt/scanner/cache
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}
      - run: |
          cp config.yml.sample /opt/scanner/config.yml
          cd /opt/scanner
          bundle exec ruby run.rb

